### ISSUE TITLE
运行infer_strat.sh时显示ValueError

### ISSUE THREAD

**Issue by fengyulin001** [thu-coai/Emotional-Support-Conversation#21]
您好，我运行infer_strat.sh时会出现下面的问题，想咨询下作者解决的方法，谢谢
Traceback (most recent call last):
  File "/root/Emotional-Support-Conversation-main/codes_zcj/prepare.py", line 36, in <module>
    toker = build_model(only_toker=True, **names)
  File "/root/Emotional-Support-Conversation-main/codes_zcj/utils/building_utils.py", line 27, in build_model
    raise ValueError
ValueError

**Comment by Ashtray4** [comment]
改一下路径（建议使用绝对路径）
