### ISSUE TITLE
运行infer_strat.sh 脚本报错

### ISSUE THREAD

**Issue by Viictte** [thu-coai/Emotional-Support-Conversation#31]
在运行infer_strat.sh脚本时每次validation结束后，会报错：

TypeError: forward() got an unexpected keyword argument 'encoder_outputs'
inferring:   0%|                                                                                                                                  | 0/195 [00:00<?, ?it/s]

是哪里出现了问题，谢谢

**Comment by Viictte** [comment]
完整trace back：
 Traceback (most recent call last):
  File "infer.py", line 191, in <module>
    encoded_info, generations = model.generate(**batch)
  File "C:\Users\Viict\miniconda3\envs\ESC\lib\site-packages\torch\autograd\grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Viict\Research\Emotional-Support-Conversation-main\Emotional-Support-Conversation-main\codes_zcj\models\strat_blenderbot_small.py", line 160, in generate
    **kwargs
  File "C:\Users\Viict\miniconda3\envs\ESC\lib\site-packages\torch\autograd\grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Viict\miniconda3\envs\ESC\lib\site-packages\transformers\generation_utils.py", line 833, in generate
    model_kwargs = self._prepare_encoder_decoder_kwargs_for_generation(input_ids, model_kwargs)
  File "C:\Users\Viict\miniconda3\envs\ESC\lib\site-packages\transformers\generation_utils.py", line 378, in _prepare_encoder_decoder_kwargs_for_generation    
    model_kwargs["encoder_outputs"]: ModelOutput = encoder(input_ids, return_dict=True, **encoder_kwargs)
  File "C:\Users\Viict\miniconda3\envs\ESC\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'encoder_outputs'

**Comment by Viictte** [comment]
环境配置的原因，找到了
