### ISSUE TITLE
KeyError: 'strategy'

### ISSUE THREAD

**Issue by lionel157** [thu-coai/Emotional-Support-Conversation#38]
执行这条指令 bash RUN/interact_strat.sh后，能对话，但是输入对话后报错，错误如下 
Traceback (most recent call last):
  File "interact.py", line 169, in <module>
    inputs = inputter.convert_data_to_inputs(history, toker, **dataloader_kwargs)
  File "/home/qlunlp/zlx/ESC/Emotional-Support-Conversation-main/codes_zcj/inputters/strat.py", line 87, in convert_data_to_inputs
    strat_id = process('[' + dialog[i]['strategy'] + ']')
KeyError: 'strategy'
![屏幕截图 2024-10-15 150839](https://github.com/user-attachments/assets/37f5e92f-dc02-482e-8245-2bfe1df57f2c)

**Comment by chujiezheng** [comment]
请参考这个issue：https://github.com/thu-coai/Emotional-Support-Conversation/issues/11
